Two changes to `bin/microjournal`, both fixes.
Lines 31-34: Fixed this error:

    Traceback (most recent call last):
      File "/Users/michael/Downloads/microjournal/bin/microjournal", line 93, in <module>
        OPTIONS.get(COMMAND, wrong_command)()
      File "/Users/michael/Downloads/microjournal/bin/microjournal", line 31, in jot
        editor = os.getenv("EDITOR").strip()
    AttributeError: 'NoneType' object has no attribute 'strip'

Line 46: Changed `git ci` to `git commit`.